name: SonarQube Analysis

on:
  push:
    branches:
      - master  # or the branch you want to analyze

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Run SonarQube Scanner
        env:
          SONAR_HOST_URL: http://3.90.58.75:9000/
          SONAR_LOGIN: squ_11899c569c990539925b502d32691d25b96a83b8
        run: npx sonarqube-scanner
